# rule identifiers to exclude from running.
disabled_rules:
  - line_length
  - trailing_comma
  - file_length
  - identifier_name
  - cyclomatic_complexity
  - todo
  - force_cast
  - force_try
  - large_tuple
  - function_body_length
  - nesting
  - opening_brace
  - function_parameter_count

# rules required to opt-in that are not by default.
opt_in_rules:
  - empty_count
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_optional_binding
  - unused_private_declaration
  - unused_enumerated
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - unavailable_function
  - type_contents_order
  - strict_fileprivate
  - static_operator
  - single_test_class
  - redundant_type_annotation
  - redundant_nil_coalescing
  - prohibited_super_call
  - pattern_matching_keywords
  - overridden_super_call
  - operator_usage_whitespace
  - object_literal
  - number_separator
  - multiline_parameters_brackets
  - multiline_parameters
  - multiline_literal_brackets
  - multiline_function_chains
  - multiline_arguments_brackets
  - multiline_arguments
  - modifier_order
  - lower_acl_than_parent
  - literal_expression_end_indentation
  - let_var_whitespace
  - legacy_random
  - first_where
  - last_where
  - joined_default_parameter
  - implicitly_unwrapped_optional
  - implicit_return
  - identical_operands
  - fatal_error_message
  - explicit_init
  - empty_string
  - empty_xctest_method
  - convenience_type
  - contains_over_first_not_nil
  - conditional_returns_on_newline
  - closure_spacing
  - closure_end_indentation
  - attributes
  - array_init
  - anyobject_protocol

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - .build
