os:
  - osx
language: objective-c
osx_image: xcode10.2
cache:
  directories:
    - .build
    - /usr/local/Homebrew
    - ~/Library/Caches/Homebrew
    - ~/.danger-swift
addons:
  homebrew:
    taps:
      - danger/tap
    packages:
      - danger-swift
      - swiftlint
script:
  - danger-swift ci
  - swift test
  - make
branches:
  only:
    - master
    - develop
notifications:
  email: false
