os:
  - osx
language: objective-c
osx_image: xcode10.2
before_install:
  - npm install -g danger
script:
  - swift run danger-swift ci
  - swift test
  - make
branches:
  only:
    - master
    - develop
notifications:
  email: false
