os:
  - osx
language: objective-c
osx_image: xcode10.2
cache:
  directories:
    - .build
    - ~/.danger-swift
addons:
  homebrew:
    packages:
      - swiftlint
install:
  - npm install -g danger@7.x
  - swift build
script:
  - swift run danger-swift ci
  - swift test
  - make
branches:
  only:
    - master
    - develop
notifications:
  email: false
