import BadondeKit

let badonde = Badonde(
	ticketType: .githubIssue(derivationStrategy: .regex),
	baseBranchDerivationStrategy: .commitProximity
)

// Set issue to convert to PR (if found).
if let githubIssue = badonde.github.issue {
	issue(githubIssue.number)
}

// Add a cheeky little watermark at the end :)
let prBody = (badonde.github.issue?.body ?? "")
	.trimmingCharacters(in: .whitespacesAndNewlines)
	.appending("\n\n")
	.appending(
		"""
		<h6 align="right">
		<img width="12" height="12" src="https://imgur.com/download/Zz8GL0X">
		Generated by <a href="https://badonde.dev">Badonde</a>
		</h6>
		"""
	)
	.trimmingCharacters(in: .whitespacesAndNewlines)

body(prBody)
