import BadondeKit

let badonde = Badonde(
	ticketType: .githubIssue(derivationStrategy: .regex),
	baseBranchDerivationStrategy: .commitProximity
)

if let githubIssue = badonde.github.issue {
	issue(githubIssue.number)

	let watermark =
		"""
		<h6 align="right">
			<img width="12" height="12" src="https://imgur.com/download/Zz8GL0X">
			Generated by <a href="https://badonde.dev">Badonde</a>
		</h6>
		"""

	let issueBody = (githubIssue.body ?? "")
		.trimmingCharacters(in: .whitespacesAndNewlines)
		.appending("\n\n")
		.appending(watermark)
		.trimmingCharacters(in: .whitespacesAndNewlines)

	body(issueBody)
}
